### ISSUE TITLE
Observability metrics not working and the PODS restart nonstop

### ISSUE THREAD

**Issue by pxchek** [pxchek/spring-boot-project#7]
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: backend
  strategy: { }
  template:
    metadata:
      labels:
        io.kompose.network/spring-boot-project: "true"
        io.kompose.service: backend
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: example
          image: spring-boot-project_backend:latest
          imagePullPolicy: Never
          name: backend
          ports:
            - containerPort: 8080
              name: backend-port
          startupProbe:
            httpGet:
              port: backend-port
              path: /
          readinessProbe:
            httpGet:
              port: backend-port
              path: /
            initialDelaySeconds: 5
          livenessProbe:
            httpGet:
              port: backend-port
              path: /
            initialDelaySeconds: 10
            periodSeconds: 30
          resources: { }
      restartPolicy: Always
```
